server:
  error:
    path: /error
  tomcat:
    accesslog:
      enabled: true
    relaxed-query-chars: '|,{,},[,]'
    relaxed-path-chars: '|,{,},[,]'
  servlet:
    encoding:
      charset: UTF-8
      force: true

logging:
  group:
    tomcat: org.apache.catalina, org.apache.coyote, org.apache.tomcat
  level:
    tomcat: OFF

spring:
  mustache:
    servlet:
      expose-request-attributes: true