server:
  error:
    path: /error
  tomcat:
    accesslog:
      enabled: true
    relaxed-query-chars: '|,{,},[,]'
    relaxed-path-chars: '|,{,},[,]'
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  mustache:
    servlet:
      expose-request-attributes: true

bot:
  username: ${BOT_USERNAME}
  token: ${BOT_TOKEN}