server:
  error:
    path: /error
  tomcat:
    accesslog:
      enabled: true
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  mustache:
    servlet:
      expose-request-attributes: true